server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/super_market?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: 123456
    driver‐class‐name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher