server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://api.maiquer.tech:3306/super_market?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2b8
    username: root
    password: maiqu
    driver‐class‐name: com.mysql.cj.jdbc.Driver
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher